# Generated by Django 4.2.8 on 2026-04-24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_import_items_detail_sale_items_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(blank=True, default='', max_length=20)),
                ('product_name', models.CharField(max_length=200)),
                ('unit', models.CharField(blank=True, default='', max_length=50)),
                ('quantity', models.IntegerField(default=0)),
                ('unit_price', models.IntegerField(default=0)),
                ('import_price', models.IntegerField(default=0)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_items', to='core.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='core.sale')),
            ],
        ),
        migrations.CreateModel(
            name='ImportItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(blank=True, default='', max_length=20)),
                ('product_name', models.CharField(max_length=200)),
                ('unit', models.CharField(blank=True, default='', max_length=50)),
                ('quantity', models.IntegerField(default=0)),
                ('unit_price', models.IntegerField(default=0)),
                ('import_price', models.IntegerField(default=0)),
                ('import_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='core.import')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_items', to='core.product')),
            ],
        ),
    ]
