# Generated by Django 4.2.8 on 2026-04-24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_migrate_transaction_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='import',
            name='items_detail',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='items_detail',
        ),
    ]
