# Generated by Django 4.2.8 on 2026-04-24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_legacy_items_detail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='date',
            new_name='date_text',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='customer',
            new_name='customer_name',
        ),
        migrations.AlterField(
            model_name='sale',
            name='customer_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='core.customer'),
        ),
        migrations.AddField(
            model_name='sale',
            name='transaction_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RenameField(
            model_name='import',
            old_name='date',
            new_name='date_text',
        ),
        migrations.RenameField(
            model_name='import',
            old_name='supplier',
            new_name='supplier_name',
        ),
        migrations.AlterField(
            model_name='import',
            name='supplier_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='import',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imports', to='core.supplier'),
        ),
        migrations.AddField(
            model_name='import',
            name='transaction_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
