# Generated by Django 4.2.8 on 2026-04-24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_backfill_partner_fk_and_dates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='date_text',
        ),
        migrations.RemoveField(
            model_name='import',
            name='date_text',
        ),
    ]
